-- SQL Schema for Supabase
-- Run this in your Supabase SQL Editor

-- 1. Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rfid_card TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Admins Table
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Books Table
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    barcode TEXT UNIQUE NOT NULL,
    image_url TEXT,
    quantity INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Book Items Table (Individual copies)
CREATE TABLE IF NOT EXISTS book_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES books(id) ON DELETE CASCADE,
    unique_code TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'available',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Borrowings Table
CREATE TABLE IF NOT EXISTS borrowings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id),
    book_item_id BIGINT REFERENCES book_items(id),
    borrow_date TIMESTAMPTZ DEFAULT NOW(),
    return_date TIMESTAMPTZ NOT NULL,
    returned BOOLEAN DEFAULT FALSE,
    returned_at TIMESTAMPTZ
);

-- 6. Security Logs Table
CREATE TABLE IF NOT EXISTS security_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES books(id),
    detection_time TIMESTAMPTZ DEFAULT NOW(),
    status TEXT NOT NULL
);

-- 7. Book Proposals Table
CREATE TABLE IF NOT EXISTS book_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id),
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    reason TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Chat Messages Table
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id),
    content TEXT NOT NULL,
    role TEXT NOT NULL, -- 'user', 'assistant', 'admin'
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Card Requests Table
CREATE TABLE IF NOT EXISTS card_requests (
    id BIGSERIAL PRIMARY KEY,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    "studentId" TEXT,
    "cardType" TEXT NOT NULL,
    status TEXT NOT NULL,
    certif_url TEXT,
    photo_url TEXT,
    request_status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and add policies
ALTER TABLE card_requests ENABLE ROW LEVEL SECURITY;

-- Allow anyone to submit a request (INSERT)
CREATE POLICY "Enable insert for all users" ON card_requests FOR INSERT WITH CHECK (true);

-- Allow admins to read all requests (assuming they use service role or we can check role if implemented)
-- For simplicity in this environment, allow all reads if RLS is on, or disable it
ALTER TABLE card_requests DISABLE ROW LEVEL SECURITY;

-- Initial Data
-- Seed admin (password: admin123)
-- INSERT INTO admins (name, email, password) VALUES ('Admin', 'admin@bibio.univ', '$2a$10$YourHashedPasswordHere');
